---

all:
  children:
    opnsense:
      hosts:
        opnsense01:
          ansible_host: 192.168.2.2
          ansible_connection: local
#          opnsense_api_host: "192.168.2.2"
#          opnsense_api_key: "{{ vault_opnsense_api_key }}"
#          opnsense_api_secret: "{{ vault_opnsense_api_secret }}"
          firewall: "192.168.2.2"
#          port: 443
          ssl_verify: false
