---
- name: "VLANs konfigurieren"
  ansibleguy.opnsense.interface_vlan:
    firewall: "{{ firewall }}"
    api_key: "{{ opnsense_api_key }}"
    api_secret: "{{ opnsense_api_secret }}"
    ssl_verify: false
    description: "{{ item.description }}"
    interface: "{{ item.interface }}"
    vlan: "{{ item.id }}"
  loop: "{{ vlans }}"
  notify: reload_interfaces

- name: "DHCP Subnets konfigurieren"
  ansibleguy.opnsense.dhcp_subnet:
    firewall: "{{ firewall }}"
    api_key: "{{ opnsense_api_key }}"
    api_secret: "{{ opnsense_api_secret }}"
    ssl_verify: false
    interface: "vlan{{ item.id }}"
    enabled: "{{ item.dhcp_enabled }}"
    range_from: "{{ item.dhcp_range_start | default(omit) }}"
    range_to: "{{ item.dhcp_range_end | default(omit) }}"
    domain: "{{ item.name }}.{{ domain_internal }}"
    dns_servers:
      - "{{ item.gateway }}"
  loop: "{{ vlans }}"
  when: item.dhcp_enabled is defined and item.dhcp_enabled

- name: "Statische DHCP Reservierungen setzen"
  ansibleguy.opnsense.dhcp_reservation:
    firewall: "{{ firewall }}"
    api_key: "{{ opnsense_api_key }}"
    api_secret: "{{ opnsense_api_secret }}"
    ssl_verify: false
    mac: "{{ item.mac }}"
    ip: "{{ item.ip }}"
    hostname: "{{ item.hostname }}"
    description: "{{ item.hostname }}"
  loop: "{{ static_leases }}"
