---
- name: "Firewall Plugin prüfen (os-firewall)"
  oxlorg.opnsense.package:
    firewall: "{{ firewall }}"
    api_key: "{{ opnsense_api_key }}"
    api_secret: "{{ opnsense_api_secret }}"
    ssl_verify: false
    name: ["os-firewall"]
    action: install

- name: "Firewall-Regeln setzen"
  oxlorg.opnsense.rule:
    firewall: "{{ firewall }}"
    api_key: "{{ opnsense_api_key }}"
    api_secret: "{{ opnsense_api_secret }}"
    ssl_verify: false
    description: "{{ item.description }}"
    source_net: "{{ item.source_net }}"
    destination_net: "{{ item.dest_net }}"
    action: "{{ item.action }}"
    protocol: "{{ item.protocol | default(omit) }}"
    destination_port: "{{ item.dest_port | default(omit) }}"
    enabled: true
    match_fields: ["description"]
  loop: "{{ firewall_rules }}"
  notify: reload_firewall

- name: "Anti-Lockout Regel"
  oxlorg.opnsense.rule:
    firewall: "{{ firewall }}"
    api_key: "{{ opnsense_api_key }}"
    api_secret: "{{ opnsense_api_secret }}"
    ssl_verify: false
    description: "Anti-Lockout OPNsense"
    source_net: "192.168.10.0/24"
    destination_net: "192.168.10.1/32"
    action: "pass"
    protocol: "TCP"
    destination_port: 443
    match_fields: ["description"]
    enabled: true
  notify: reload_firewall