---
- name: reload_interfaces
  oxlorg.opnsense.reload:
    firewall: "{{ firewall }}"
    api_key: "{{ opnsense_api_key }}"
    api_secret: "{{ opnsense_api_secret }}"
    ssl_verify: false
    target: "interface_vlan"
