---

- name: "Unbound DNS konfigurieren"
  ansibleguy.opnsense.unbound_general:
    firewall: "{{ firewall }}"
    api_key: "{{ opnsense_api_key }}"
    api_secret: "{{ opnsense_api_secret }}"
    ssl_verify: false
    enabled: true
    port: 53
    dnssec: true

- name: "Unbound Forwarder – Quad9 DoT"
  ansibleguy.opnsense.unbound_forward:
    firewall: "{{ firewall }}"
    api_key: "{{ opnsense_api_key }}"
    api_secret: "{{ opnsense_api_secret }}"
    ssl_verify: false
#    domain: "."
    enabled: true
    target: "9.9.9.9"

- name: "Unbound Forwarder – Quad9 Secondary"
  ansibleguy.opnsense.unbound_forward:
    firewall: "{{ firewall }}"
    api_key: "{{ opnsense_api_key }}"
    api_secret: "{{ opnsense_api_secret }}"
    ssl_verify: false
#    domain: "."
    enabled: true
    target: "149.112.112.112"
