---
- name: "OPNsense – Nur Interfaces"
  hosts: opnsense
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../group_vars/opnsense/secrets.yml"
    - "{{ playbook_dir }}/../group_vars/opnsense/vars.yml"
    - "{{ playbook_dir }}/../group_vars/all/vars.yml"
  vars:
    opnsense_api_key: "{{ vault_opnsense_api_key }}"
    opnsense_api_secret: "{{ vault_opnsense_api_secret }}"
  roles:
    - opnsense_interfaces
