---
# playbooks/vlans.yml
- name: "OPNsense – Nur VLANs"
  hosts: opnsense
  gather_facts: false
  vars_files:
    - "../group_vars/opnsense/secrets.yml"
  vars:
    opnsense_api_key: "{{ vault_opnsense_api_key }}"
    opnsense_api_secret: "{{ vault_opnsense_api_secret }}"
  roles:
    - opnsense_vlans
